[package]
name = "dihardts_cstools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
bitvec = "1.0.1"
hdf5 = "0.8.1"
murmur3 = "0.5.2"
